### ISSUE TITLE
catalog-manager-importer Trennzeichen Komma für Erkennung der Kopfzeilen 

### ISSUE THREAD

**Issue by pitsol-jheidenreich** [alnv/catalog-manager-importer#1]
Hallo Alexander,

wie auch schon ein anderer User auf der [Feedbackseite](https://catalog-manager.alexandernaumov.de/feedback/nur-komma-als-trennzeichen-beim-catalog-manager-importer.html) festgestellt hat, funktioniert der Import mit einem anderen Trennzeichen als dem Komma noch nicht vollständig. So geht für das Erkennen der Kopfzeilen einer CSV-Datei nur das Komma, unabhängig, was man sonst als Trennzeichen festgelegt hat. Wenn man nur die Kopfzeile entsprechend mit Kommata versieht, geht aber auch der Rest wieder mit dem abweichend eingestellten Trennzeichen.

Grüße 
Johannes

**Comment by alnv** [comment]
Ist gefixt in v1.1.3
