### ISSUE TITLE
Import blob images

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager-importer#4]
Hi Alex,
I like to bulk upload images as part of my csv file by filename reference.
Is this possible using the import module?

Thanks,
Rob

**Comment by alnv** [comment]
yes, you have the FILE Datatype for images. See https://catalog-manager.org/dokumentation/catalog-manager-csv-import.html.

All your pictures should be on the server. The path in your CSV must match the relative path on the server.

**Comment by robvis** [comment]
Hi Alex,
Thx for your reply.
I tried relative path (files/tao/pictures/producten/bladerdeegroosje.jpg) and absolute path as well, but neither work.
Do you have another suggestion?
Regards,
Rob

**Comment by alnv** [comment]
How are the files stored in the CSV?

**Comment by robvis** [comment]
Hi Alex,
See attached screen.
![ScreenHunter 06](https://user-images.githubusercontent.com/32883690/78573642-3f58d500-7829-11ea-88f4-5f0861bb9afd.png)

**Comment by robvis** [comment]
Please also find a screenshot from the field definition.
![ScreenHunter 07](https://user-images.githubusercontent.com/32883690/78574221-f8b7aa80-7829-11ea-8f46-ec2924213f99.png)

**Comment by robvis** [comment]
Hi Alex,
I did an upgrade from Catalog Manager modules.
Now it's running fine I see, my pictures are showing up.
Sorry for this inconvenience.
